enum Actions {
    UPDATE_CALENDAR_DETAILS = "UPDATE_CALENDAR_DETAILS",
    UPDATE_CALENDAR_DETAILS_DESCRIPTION = "UPDATE_CALENDAR_DETAILS_DESCRIPTION",
    UPDATE_REMAINING = "UPDATE_REMAINING",
    UPDATE_CATEGORIES = "UPDATE_CATEGORIES",
    UPDATE_SOURCES = "UPDATE_SOURCE",
    UPDATE_MONTH = "UPDATE_MONTH"
}

export { Actions };