enum Actions {
    UPDATE_CALENDAR_DETAILS = "UPDATE_CALENDAR_DETAILS",
    UPDATE_CALENDAR_DETAILS_DESCRIPTION = "UPDATE_CALENDAR_DETAILS_DESCRIPTION",
    UPDATE_REMAINING = "UPDATE_REMAINING"
}

export { Actions };